### ISSUE TITLE
Exposing a DCAT-AP compatible endpoint for the European Data Portal

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-dataset-harvester#44]
Hentet fra behov:
https://github.com/Informasjonsforvaltning/behov/issues/93

- [x] Utforsk om vi allerede har en tjeneste vi kan bruke til dette i dag

- [ ] Opprette et Dcat ap endepunkt

- [ ] eksponere dcat ap datasett

- [ ] mapping fra LOS-temaer til EU-temaer

**Comment by shenluna** [comment]
Denne er realisert. Vi blir nå høstet av EU, se https://data.europa.eu/data/datasets?page=1&locale=en&catalog=data-norge-no&query=
Lukker dermed saken.
